# Prepares quicktype-generated Go types for go-enum (https://github.com/abice/go-enum):
#   - adds a `// ENUM(...)` annotation above every string enum type, built from the constants quicktype generated
#   - marks quicktype's constants as deprecated in favor of the stable, type-prefixed ones generated by go-enum
#   - drops quicktype constants identical to the ones go-enum generates (e.g. BytesEncodingOther)
#
# usage: awk -f annotate-go-enums.awk types.go types.go > types.go.tmp
# (the file is read twice: the first pass collects enum values, the second one rewrites the file)

# go-enum constant name suffix for a value: capitalize the first letter and any letter following a digit
# (e.g. mainnet -> Mainnet, beaconOf -> BeaconOf, 0xhex -> 0Xhex)
function goenum_suffix(v,    out, i, c, prev) {
    out = ""
    prev = ""
    for (i = 1; i <= length(v); i++) {
        c = substr(v, i, 1)
        if (i == 1 || prev ~ /[0-9]/) c = toupper(c)
        out = out c
        prev = c
    }
    return out
}

# pass 1: collect enum values from `<Name> <Type> = "<value>"` lines
FNR == NR {
    if (match($0, /^\t[A-Za-z0-9_]+ +[A-Za-z0-9_]+ += +"[^"]*"$/)) {
        type = $2
        value = $0
        sub(/^[^"]*"/, "", value)
        sub(/"$/, "", value)
        values[type] = (type in values) ? values[type] ", " value : value
    }
    next
}

# pass 2
/^type [A-Za-z0-9_]+ string$/ && ($2 in values) {
    print "// ENUM(" values[$2] ")"
    print
    next
}

/^\t[A-Za-z0-9_]+ +[A-Za-z0-9_]+ += +"[^"]*"$/ && ($2 in values) {
    name = $1
    type = $2
    value = $0
    sub(/^[^"]*"/, "", value)
    sub(/"$/, "", value)
    replacement = type goenum_suffix(value)
    # exactly the constant go-enum generates (same name and value), so drop the duplicate
    if (name == replacement) next
    print "\t// Deprecated: use " replacement " instead."
    print
    next
}

{ print }
