// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package registry

import (
	"fmt"
	"strings"
)

const (
	// APIURLKindBlockscout is a APIURLKind of type blockscout.
	APIURLKindBlockscout APIURLKind = "blockscout"
	// APIURLKindEtherscan is a APIURLKind of type etherscan.
	APIURLKindEtherscan APIURLKind = "etherscan"
	// APIURLKindEthplorer is a APIURLKind of type ethplorer.
	APIURLKindEthplorer APIURLKind = "ethplorer"
	// APIURLKindOther is a APIURLKind of type other.
	APIURLKindOther APIURLKind = "other"
	// APIURLKindSubscan is a APIURLKind of type subscan.
	APIURLKindSubscan APIURLKind = "subscan"
)

var ErrInvalidAPIURLKind = fmt.Errorf("not a valid APIURLKind, try [%s]", strings.Join(_APIURLKindNames, ", "))

var _APIURLKindNames = []string{
	string(APIURLKindBlockscout),
	string(APIURLKindEtherscan),
	string(APIURLKindEthplorer),
	string(APIURLKindOther),
	string(APIURLKindSubscan),
}

// APIURLKindNames returns a list of possible string values of APIURLKind.
func APIURLKindNames() []string {
	tmp := make([]string, len(_APIURLKindNames))
	copy(tmp, _APIURLKindNames)
	return tmp
}

// APIURLKindValues returns a list of the values for APIURLKind
func APIURLKindValues() []APIURLKind {
	return []APIURLKind{
		APIURLKindBlockscout,
		APIURLKindEtherscan,
		APIURLKindEthplorer,
		APIURLKindOther,
		APIURLKindSubscan,
	}
}

// String implements the Stringer interface.
func (x APIURLKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x APIURLKind) IsValid() bool {
	_, err := ParseAPIURLKind(string(x))
	return err == nil
}

var _APIURLKindValue = map[string]APIURLKind{
	"blockscout": APIURLKindBlockscout,
	"etherscan":  APIURLKindEtherscan,
	"ethplorer":  APIURLKindEthplorer,
	"other":      APIURLKindOther,
	"subscan":    APIURLKindSubscan,
}

// ParseAPIURLKind attempts to convert a string to a APIURLKind.
func ParseAPIURLKind(name string) (APIURLKind, error) {
	if x, ok := _APIURLKindValue[name]; ok {
		return x, nil
	}
	return APIURLKind(""), fmt.Errorf("%s is %w", name, ErrInvalidAPIURLKind)
}

const (
	// BytesEncodingBase58 is a BytesEncoding of type base58.
	BytesEncodingBase58 BytesEncoding = "base58"
	// BytesEncodingBase64 is a BytesEncoding of type base64.
	BytesEncodingBase64 BytesEncoding = "base64"
	// BytesEncodingOther is a BytesEncoding of type other.
	BytesEncodingOther BytesEncoding = "other"
	// BytesEncodingHex is a BytesEncoding of type hex.
	BytesEncodingHex BytesEncoding = "hex"
	// BytesEncoding0Xhex is a BytesEncoding of type 0xhex.
	BytesEncoding0Xhex BytesEncoding = "0xhex"
)

var ErrInvalidBytesEncoding = fmt.Errorf("not a valid BytesEncoding, try [%s]", strings.Join(_BytesEncodingNames, ", "))

var _BytesEncodingNames = []string{
	string(BytesEncodingBase58),
	string(BytesEncodingBase64),
	string(BytesEncodingOther),
	string(BytesEncodingHex),
	string(BytesEncoding0Xhex),
}

// BytesEncodingNames returns a list of possible string values of BytesEncoding.
func BytesEncodingNames() []string {
	tmp := make([]string, len(_BytesEncodingNames))
	copy(tmp, _BytesEncodingNames)
	return tmp
}

// BytesEncodingValues returns a list of the values for BytesEncoding
func BytesEncodingValues() []BytesEncoding {
	return []BytesEncoding{
		BytesEncodingBase58,
		BytesEncodingBase64,
		BytesEncodingOther,
		BytesEncodingHex,
		BytesEncoding0Xhex,
	}
}

// String implements the Stringer interface.
func (x BytesEncoding) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BytesEncoding) IsValid() bool {
	_, err := ParseBytesEncoding(string(x))
	return err == nil
}

var _BytesEncodingValue = map[string]BytesEncoding{
	"base58": BytesEncodingBase58,
	"base64": BytesEncodingBase64,
	"other":  BytesEncodingOther,
	"hex":    BytesEncodingHex,
	"0xhex":  BytesEncoding0Xhex,
}

// ParseBytesEncoding attempts to convert a string to a BytesEncoding.
func ParseBytesEncoding(name string) (BytesEncoding, error) {
	if x, ok := _BytesEncodingValue[name]; ok {
		return x, nil
	}
	return BytesEncoding(""), fmt.Errorf("%s is %w", name, ErrInvalidBytesEncoding)
}

const (
	// FeatureDexes is a Feature of type dexes.
	FeatureDexes Feature = "dexes"
	// FeatureOther is a Feature of type other.
	FeatureOther Feature = "other"
	// FeatureNfts is a Feature of type nfts.
	FeatureNfts Feature = "nfts"
	// FeatureTokens is a Feature of type tokens.
	FeatureTokens Feature = "tokens"
)

var ErrInvalidFeature = fmt.Errorf("not a valid Feature, try [%s]", strings.Join(_FeatureNames, ", "))

var _FeatureNames = []string{
	string(FeatureDexes),
	string(FeatureOther),
	string(FeatureNfts),
	string(FeatureTokens),
}

// FeatureNames returns a list of possible string values of Feature.
func FeatureNames() []string {
	tmp := make([]string, len(_FeatureNames))
	copy(tmp, _FeatureNames)
	return tmp
}

// FeatureValues returns a list of the values for Feature
func FeatureValues() []Feature {
	return []Feature{
		FeatureDexes,
		FeatureOther,
		FeatureNfts,
		FeatureTokens,
	}
}

// String implements the Stringer interface.
func (x Feature) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Feature) IsValid() bool {
	_, err := ParseFeature(string(x))
	return err == nil
}

var _FeatureValue = map[string]Feature{
	"dexes":  FeatureDexes,
	"other":  FeatureOther,
	"nfts":   FeatureNfts,
	"tokens": FeatureTokens,
}

// ParseFeature attempts to convert a string to a Feature.
func ParseFeature(name string) (Feature, error) {
	if x, ok := _FeatureValue[name]; ok {
		return x, nil
	}
	return Feature(""), fmt.Errorf("%s is %w", name, ErrInvalidFeature)
}

const (
	// NetworkTypeBeacon is a NetworkType of type beacon.
	NetworkTypeBeacon NetworkType = "beacon"
	// NetworkTypeDevnet is a NetworkType of type devnet.
	NetworkTypeDevnet NetworkType = "devnet"
	// NetworkTypeMainnet is a NetworkType of type mainnet.
	NetworkTypeMainnet NetworkType = "mainnet"
	// NetworkTypeTestnet is a NetworkType of type testnet.
	NetworkTypeTestnet NetworkType = "testnet"
)

var ErrInvalidNetworkType = fmt.Errorf("not a valid NetworkType, try [%s]", strings.Join(_NetworkTypeNames, ", "))

var _NetworkTypeNames = []string{
	string(NetworkTypeBeacon),
	string(NetworkTypeDevnet),
	string(NetworkTypeMainnet),
	string(NetworkTypeTestnet),
}

// NetworkTypeNames returns a list of possible string values of NetworkType.
func NetworkTypeNames() []string {
	tmp := make([]string, len(_NetworkTypeNames))
	copy(tmp, _NetworkTypeNames)
	return tmp
}

// NetworkTypeValues returns a list of the values for NetworkType
func NetworkTypeValues() []NetworkType {
	return []NetworkType{
		NetworkTypeBeacon,
		NetworkTypeDevnet,
		NetworkTypeMainnet,
		NetworkTypeTestnet,
	}
}

// String implements the Stringer interface.
func (x NetworkType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x NetworkType) IsValid() bool {
	_, err := ParseNetworkType(string(x))
	return err == nil
}

var _NetworkTypeValue = map[string]NetworkType{
	"beacon":  NetworkTypeBeacon,
	"devnet":  NetworkTypeDevnet,
	"mainnet": NetworkTypeMainnet,
	"testnet": NetworkTypeTestnet,
}

// ParseNetworkType attempts to convert a string to a NetworkType.
func ParseNetworkType(name string) (NetworkType, error) {
	if x, ok := _NetworkTypeValue[name]; ok {
		return x, nil
	}
	return NetworkType(""), fmt.Errorf("%s is %w", name, ErrInvalidNetworkType)
}

const (
	// ProtocolArweave is a Protocol of type arweave.
	ProtocolArweave Protocol = "arweave"
	// ProtocolCosmos is a Protocol of type cosmos.
	ProtocolCosmos Protocol = "cosmos"
	// ProtocolEthereum is a Protocol of type ethereum.
	ProtocolEthereum Protocol = "ethereum"
	// ProtocolNear is a Protocol of type near.
	ProtocolNear Protocol = "near"
	// ProtocolOther is a Protocol of type other.
	ProtocolOther Protocol = "other"
	// ProtocolStarknet is a Protocol of type starknet.
	ProtocolStarknet Protocol = "starknet"
)

var ErrInvalidProtocol = fmt.Errorf("not a valid Protocol, try [%s]", strings.Join(_ProtocolNames, ", "))

var _ProtocolNames = []string{
	string(ProtocolArweave),
	string(ProtocolCosmos),
	string(ProtocolEthereum),
	string(ProtocolNear),
	string(ProtocolOther),
	string(ProtocolStarknet),
}

// ProtocolNames returns a list of possible string values of Protocol.
func ProtocolNames() []string {
	tmp := make([]string, len(_ProtocolNames))
	copy(tmp, _ProtocolNames)
	return tmp
}

// ProtocolValues returns a list of the values for Protocol
func ProtocolValues() []Protocol {
	return []Protocol{
		ProtocolArweave,
		ProtocolCosmos,
		ProtocolEthereum,
		ProtocolNear,
		ProtocolOther,
		ProtocolStarknet,
	}
}

// String implements the Stringer interface.
func (x Protocol) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Protocol) IsValid() bool {
	_, err := ParseProtocol(string(x))
	return err == nil
}

var _ProtocolValue = map[string]Protocol{
	"arweave":  ProtocolArweave,
	"cosmos":   ProtocolCosmos,
	"ethereum": ProtocolEthereum,
	"near":     ProtocolNear,
	"other":    ProtocolOther,
	"starknet": ProtocolStarknet,
}

// ParseProtocol attempts to convert a string to a Protocol.
func ParseProtocol(name string) (Protocol, error) {
	if x, ok := _ProtocolValue[name]; ok {
		return x, nil
	}
	return Protocol(""), fmt.Errorf("%s is %w", name, ErrInvalidProtocol)
}

const (
	// RelationKindBeaconOf is a RelationKind of type beaconOf.
	RelationKindBeaconOf RelationKind = "beaconOf"
	// RelationKindEvmOf is a RelationKind of type evmOf.
	RelationKindEvmOf RelationKind = "evmOf"
	// RelationKindOther is a RelationKind of type other.
	RelationKindOther RelationKind = "other"
	// RelationKindForkedFrom is a RelationKind of type forkedFrom.
	RelationKindForkedFrom RelationKind = "forkedFrom"
	// RelationKindL2Of is a RelationKind of type l2Of.
	RelationKindL2Of RelationKind = "l2Of"
	// RelationKindShardOf is a RelationKind of type shardOf.
	RelationKindShardOf RelationKind = "shardOf"
	// RelationKindSvmOf is a RelationKind of type svmOf.
	RelationKindSvmOf RelationKind = "svmOf"
	// RelationKindTestnetOf is a RelationKind of type testnetOf.
	RelationKindTestnetOf RelationKind = "testnetOf"
)

var ErrInvalidRelationKind = fmt.Errorf("not a valid RelationKind, try [%s]", strings.Join(_RelationKindNames, ", "))

var _RelationKindNames = []string{
	string(RelationKindBeaconOf),
	string(RelationKindEvmOf),
	string(RelationKindOther),
	string(RelationKindForkedFrom),
	string(RelationKindL2Of),
	string(RelationKindShardOf),
	string(RelationKindSvmOf),
	string(RelationKindTestnetOf),
}

// RelationKindNames returns a list of possible string values of RelationKind.
func RelationKindNames() []string {
	tmp := make([]string, len(_RelationKindNames))
	copy(tmp, _RelationKindNames)
	return tmp
}

// RelationKindValues returns a list of the values for RelationKind
func RelationKindValues() []RelationKind {
	return []RelationKind{
		RelationKindBeaconOf,
		RelationKindEvmOf,
		RelationKindOther,
		RelationKindForkedFrom,
		RelationKindL2Of,
		RelationKindShardOf,
		RelationKindSvmOf,
		RelationKindTestnetOf,
	}
}

// String implements the Stringer interface.
func (x RelationKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RelationKind) IsValid() bool {
	_, err := ParseRelationKind(string(x))
	return err == nil
}

var _RelationKindValue = map[string]RelationKind{
	"beaconOf":   RelationKindBeaconOf,
	"evmOf":      RelationKindEvmOf,
	"other":      RelationKindOther,
	"forkedFrom": RelationKindForkedFrom,
	"l2Of":       RelationKindL2Of,
	"shardOf":    RelationKindShardOf,
	"svmOf":      RelationKindSvmOf,
	"testnetOf":  RelationKindTestnetOf,
}

// ParseRelationKind attempts to convert a string to a RelationKind.
func ParseRelationKind(name string) (RelationKind, error) {
	if x, ok := _RelationKindValue[name]; ok {
		return x, nil
	}
	return RelationKind(""), fmt.Errorf("%s is %w", name, ErrInvalidRelationKind)
}

const (
	// SubgraphKindBackstop is a SubgraphKind of type backstop.
	SubgraphKindBackstop SubgraphKind = "backstop"
	// SubgraphKindGateway is a SubgraphKind of type gateway.
	SubgraphKindGateway SubgraphKind = "gateway"
	// SubgraphKindStudio is a SubgraphKind of type studio.
	SubgraphKindStudio SubgraphKind = "studio"
)

var ErrInvalidSubgraphKind = fmt.Errorf("not a valid SubgraphKind, try [%s]", strings.Join(_SubgraphKindNames, ", "))

var _SubgraphKindNames = []string{
	string(SubgraphKindBackstop),
	string(SubgraphKindGateway),
	string(SubgraphKindStudio),
}

// SubgraphKindNames returns a list of possible string values of SubgraphKind.
func SubgraphKindNames() []string {
	tmp := make([]string, len(_SubgraphKindNames))
	copy(tmp, _SubgraphKindNames)
	return tmp
}

// SubgraphKindValues returns a list of the values for SubgraphKind
func SubgraphKindValues() []SubgraphKind {
	return []SubgraphKind{
		SubgraphKindBackstop,
		SubgraphKindGateway,
		SubgraphKindStudio,
	}
}

// String implements the Stringer interface.
func (x SubgraphKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SubgraphKind) IsValid() bool {
	_, err := ParseSubgraphKind(string(x))
	return err == nil
}

var _SubgraphKindValue = map[string]SubgraphKind{
	"backstop": SubgraphKindBackstop,
	"gateway":  SubgraphKindGateway,
	"studio":   SubgraphKindStudio,
}

// ParseSubgraphKind attempts to convert a string to a SubgraphKind.
func ParseSubgraphKind(name string) (SubgraphKind, error) {
	if x, ok := _SubgraphKindValue[name]; ok {
		return x, nil
	}
	return SubgraphKind(""), fmt.Errorf("%s is %w", name, ErrInvalidSubgraphKind)
}
